version: '2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - esdata:/usr/share/elasticsearch/data
        networks:
            - esnetwork
    kibana:
        image: docker.elastic.co/kibana/kibana:6.3.0
        ports:
            - "5601:5601"
        networks:
            - esnetwork
        depends_on:
            - elasticsearch
    postgresql:
        image: 'bitnami/postgresql:latest'
        ports:
            - '5444:5432'
        volumes:
            - 'postgresql_data:/bitnami'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
    sonarqube:
        image: bitnami/sonarqube:latest
        ports:
            - '9999:9000'
        environment:
            - POSTGRESQL_HOST=postgresql
            - POSTGRESQL_PORT=5444
            - POSTGRESQL_ROOT_USER=postgres
            - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_sonarqube
            - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_sonarqube
            - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=""
            - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
            - SONARQUBE_DATABASE_USER=bn_sonarqube
            - SONARQUBE_DATABASE_PASSWORD=bitnami1234
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - sonarqube_data:/bitnami
volumes:
    esdata:
        driver: local
    sonarqube_data:
        driver: local
    postgresql_data:
        driver: local
networks:
    esnetwork:
        driver: bridge